[package]
name = "skim"
version = "0.9.4"
authors = ["Zhang Jinzhou <lotabout@gmail.com>"]
description = "Fuzzy Finder in rust!"
documentation = "https://docs.rs/skim"
homepage = "https://github.com/lotabout/skim"
repository = "https://github.com/lotabout/skim"
readme  = "README.md"
keywords = ["fuzzy", "menu", "util"]
license = "MIT"
edition = "2018"

[lib]
name = "skim"
path = "src/lib.rs"

[[bin]]
name = "sk"
path = "src/bin/main.rs"

[dependencies]
nix = "0.22.1"
atty = "0.2.14"
regex = "1.5.4"
lazy_static = "1.4.0"
shlex = "1.0.0"
unicode-width = "0.1.8"
log = "0.4.14"
env_logger = "0.9.0"
time = "0.3.1"
clap = "2.33.3"
tuikit = "0.4.5"
vte = "0.10.1"
fuzzy-matcher = "0.3.7"
rayon = "1.5.1"
derive_builder = "0.9"
bitflags = "1.2.1"
timer = "0.2.0"
chrono = "0.4.19"
crossbeam = "0.8.1"
beef = "0.5.1" # compact cow
defer-drop = "1.0.1"

[features]
default = []

[profile.release]
lto = true
debug = false
